### ISSUE TITLE
The meaning of CPI

### ISSUE THREAD

**Issue by greenonline** [owenRiddy/cataclysm-mouse#2]
This is not a bug but could serve as an amendment to the `testcase.mouse`.

Currently it says:

> == Set the CPI ==
> I don't know what it stands for - something per inch. Low numbers means the mouse moves further with a small wrist flick. Use integers. I tried 1 to 20.

CPI stands for **Counts per inch** which are different from **Dots per inch**.

It is explained fully in a blog on the SteelSeries website, [Why Higher CPI Doesn't Mean Better](https://steelseries.com/blog/the-cpi-lie-18):

> Simply put, CPI is an acronym for Counts Per Inch, and often mislabeled as DPI, or Dots Per Inch. In other words, with a CPI setting of 800, a one-inch movement of your mouse moves your cursor 800 pixels.

**Comment by owenRiddy** [comment]
I have linked the blog post in `testcase.mouse`. Thanks for clearing that up.
